apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: gcr.io/deployment-k8s-gke-demo/springboot-k8s-app:1.1
          # Image that will be used to containers in the cluster
          ports:
            - containerPort: 8080
# The port that the container is running on in the cluster