apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          # Use the dynamic IMAGE_NAME set in the GitHub Actions workflow
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/springboot-k8s-app:springboot-k8s-app-${{ github.sha }}
          ports:
            - containerPort: 8080
