name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (skip tests)
        run: |
          mvn clean package -DskipTests

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      # Authenticate Docker to GitHub Container Registry
      - name: Log in to GitHub Container Registry (GHCR)
        env:
          USERNAME: ${{ secrets.GITHUB_USERNAME }}  # Your GitHub username
          PASSWORD: ${{ secrets.GITHUB_PASSWORD }}  # Your PAT (Personal Access Token)
        run: |
          echo $GITHUB_PASSWORD | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/springboot-k8s-app:1.0
          docker build -t $IMAGE_NAME .

      # Push Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push $IMAGE_NAME

      # Install kubectl for GKE deployment
      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Get GKE credentials
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --zone ${{ secrets.GKE_CLUSTER_ZONE }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

      # Deploy to GKE using kubectl
      - name: Deploy to GKE
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
