name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      REGION: us
      IMAGE_TAG: springboot-k8s-app-${{ github.sha }}
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID | lower }}/springboot-k8s-app:${{ env.IMAGE_TAG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (skip tests)
        run: |
          mvn clean package -DskipTests

      - name: Authenticate with Google Cloud using Service Account Key
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Docker auth
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          echo "Building Docker image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .

      - name: Push Docker image to Artifact Registry
        run: |
          echo "Pushing Docker image: $IMAGE_NAME"
          docker push $IMAGE_NAME

      - name: Update image in deployment.yaml
        run: |
          echo "Updating image in deployment.yaml to $IMAGE_NAME"
          sed -i "s|gcr.io/${{ secrets.GCP_PROJECT_ID }}/springboot-k8s-app:.*|$IMAGE_NAME|" deployment.yaml

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
