name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      REGION: us
      IMAGE_NAME: us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr.io/springboot-k8s-app:springboot-k8s-app-${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (skip tests)
        run: |
          mvn clean package -DskipTests

      # List files in target directory for debugging
      - name: List files in target folder
        run: |
          ls -al target

      - name: Authenticate with Google Cloud using Service Account Key
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Docker auth
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push $IMAGE_NAME

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --zone us-central1-a \
          --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Replace image tag in deployment.yaml
        run: |
          IMAGE_TAG="springboot-k8s-app-${{ github.sha }}"
          sed -i "s|gcr.io/${{ secrets.GCP_PROJECT_ID }}/springboot-k8s-app:.*|gcr.io/${{ secrets.GCP_PROJECT_ID }}/springboot-k8s-app:${IMAGE_TAG}|" deployment.yaml

      - name: Deploy to GKE
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
